local system = require 'pandoc.system'

local table_dir_name = 'table-gen'
local table_dir_path = system.get_working_directory() .. '/' .. table_dir_name
os.execute('mkdir -p "' .. table_dir_path .. '"')

local function file_exists(name)
  local f = io.open(name, 'r')
  if f ~= nil then
    io.close(f)
    return true
  else
    return false
  end
end

local function read_file(path)
  local f = io.open(path, 'r')
  if f == nil then
    io.stderr:write(string.format("LaTeXML: Could not open file '%s'\n", path))
    return nil
  end
  local content = f:read('*all')
  f:close()
  return content
end

local function latex2html(tex_content, outfile)
  local cwd = system.get_working_directory()
  local success = false

  system.with_temporary_directory('latex2html', function (tmpdir)
    -- Write the .tex file to temp directory
    local tex_file = tmpdir .. '/table.tex'
    local f = io.open(tex_file, 'w')
    f:write(tex_content)
    f:close()

    -- Run latexml to convert tex to xml
    local xml_file = tmpdir .. '/table.xml'
    io.stderr:write(string.format("LaTeXML: Running latexml '%s' --dest='%s'\n", tex_file, xml_file))
    local latexml_cmd = string.format('latexml "%s" --dest="%s" 2>&1', tex_file, xml_file)
    os.execute(latexml_cmd)

    if not file_exists(xml_file) then
      io.stderr:write("LaTeXML: latexml failed to generate XML file\n")
      return
    end

    -- Run latexmlpost to convert xml to html (generate in tmpdir first, then copy)
    local tmp_html = tmpdir .. '/table.html'
    io.stderr:write(string.format("LaTeXML: Running latexmlpost '%s' --dest='%s'\n", xml_file, tmp_html))
    local latexmlpost_cmd = string.format('latexmlpost "%s" --dest="%s" --format=html5 2>&1',
                                          xml_file, tmp_html)
    os.execute(latexmlpost_cmd)

    if not file_exists(tmp_html) then
      io.stderr:write("LaTeXML: latexmlpost failed to generate HTML file\n")
      return
    end

    -- Copy the HTML file to the output location
    os.execute(string.format('cp "%s" "%s"', tmp_html, outfile))

    -- Copy CSS files generated by LaTeXML to the table-gen directory
    local outdir = outfile:match("(.*/)") or "./"
    for _, css_file in ipairs({"LaTeXML.css", "ltx-article.css"}) do
      local src_css = tmpdir .. '/' .. css_file
      local dest_css = outdir .. css_file
      if file_exists(src_css) then
        os.execute(string.format('cp "%s" "%s"', src_css, dest_css))
      end
    end

    success = true
  end)

  return success
end

local function extract_table_html(html_file)
  -- Read the generated HTML and extract the styles and table content
  local html_content = read_file(html_file)
  if not html_content then
    return nil
  end

  -- Extract CSS from <head> section
  local styles = ""
  for style_link in html_content:gmatch('<link[^>]*rel="stylesheet"[^>]*>') do
    -- Extract the href to get the CSS file path
    local css_href = style_link:match('href="([^"]+)"')
    if css_href then
      -- Read the CSS file from the same directory as the HTML file
      local html_dir = html_file:match("(.*/)")
      local css_file = html_dir .. css_href
      local css_content = read_file(css_file)
      if css_content then
        styles = styles .. "<style>\n" .. css_content .. "\n</style>\n"
      end
    end
  end

  -- Extract content between <body> tags
  local body_content = html_content:match('<body[^>]*>(.-)</body>') or html_content

  -- Remove LaTeXML footer (the ltx_page_footer div)
  body_content = body_content:gsub('<footer class="ltx_page_footer">.-</footer>', '')

  -- Combine styles and body content
  return styles .. body_content
end

function RawBlock(el)
  if el.format ~= "latex" and el.format ~= "tex" then
    return el
  end

  io.stderr:write(string.format("LaTeXML DEBUG: RawBlock format=%s, text_start=%s\n",
                                el.format, el.text:sub(1, 50)))

  -- Check for \table{...} command
  -- The content inside might be expanded by pandocBeamer already
  local table_match = el.text:match('^\\table%{(.+)%}$')

  if table_match then
    io.stderr:write(string.format("LaTeXML DEBUG: Found \\table{} command, content_start=%s\n",
                                  table_match:sub(1, 50)))

    -- The content is the LaTeX table code (already expanded from \cat{})
    local tex_content = table_match

    -- Generate a cache filename based on content hash
    local hash = pandoc.sha1(tex_content)
    local html_filename = hash .. '.html'
    local html_filepath = table_dir_path .. '/' .. html_filename

    -- Check if cached HTML exists
    if not file_exists(html_filepath) then
      io.stderr:write(string.format("LaTeXML: Generating HTML for table (hash: %s)\n", hash))
      local success = latex2html(tex_content, html_filepath)
      if not success then
        io.stderr:write("LaTeXML ERROR: Failed to convert table to HTML\n")
        return el
      end
    else
      io.stderr:write(string.format("LaTeXML: Using cached HTML (hash: %s)\n", hash))
    end

    -- Extract the table HTML
    local table_html = extract_table_html(html_filepath)
    if not table_html then
      io.stderr:write("LaTeXML ERROR: Failed to extract table HTML\n")
      return el
    end

    -- Return as a RawBlock of HTML that pandoc will parse
    return pandoc.RawBlock('html', table_html)
  end

  return el
end
