.PHONY: default

default:
	pandocBeamer --html slides.md 
# 	&& pdftocairo -png /home/t/Downloads/Tommaso_Pacciani___P4DDG___Slides_GPCE.pdf img-gen/gpce && python3 append_pdf.py slides.html img-gen/gpce-*.png